# Generated by Django 5.0.2 on 2026-02-27 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='markrecord',
            unique_together={('batch', 'student', 'subject')},
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('feature', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('role', 'feature')},
            },
        ),
        migrations.CreateModel(
            name='StudentTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('TO DO', 'To Do'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='TO DO', max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='registry.academictask')),
            ],
            options={
                'unique_together': {('task', 'student')},
            },
        ),
    ]
