# Generated by Django 5.0.2 on 2026-02-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_chatmessage_email_institutionalsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
