# Generated by Django 5.0.2 on 2026-02-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_email_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_snoozed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
    ]
