# Generated by Django 5.0.2 on 2026-02-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_email_is_archived_email_is_snoozed_email_is_spam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='question_papers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
