# Generated by Django 5.0.2 on 2026-03-10 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_user_city_user_country_user_district_user_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('test_type', models.CharField(choices=[('UNIT_TEST', 'Unit Test'), ('INTERNAL_I', 'Internal I'), ('INTERNAL_II', 'Internal II'), ('SEMESTER', 'Semester')], default='UNIT_TEST', max_length=20)),
                ('target_year', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('lessons', models.JSONField(blank=True, default=list)),
                ('total_marks', models.IntegerField(default=100)),
                ('duration', models.CharField(max_length=50)),
                ('questions_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Active', 'Active'), ('Completed', 'Completed')], default='Upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='registry.academicbatch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_tests', to='registry.course')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_tests', to=settings.AUTH_USER_MODEL)),
                ('subject_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_tests', to='registry.subject')),
            ],
        ),
    ]
