# Generated by Django 5.0.2 on 2026-03-11 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_user_batch_user_course_membershiprequest_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattendance',
            name='assigned_invigilator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_examinees', to=settings.AUTH_USER_MODEL),
        ),
    ]
