# Generated by Django 5.0.2 on 2026-03-17 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_testattendance_assigned_invigilator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('category', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=150)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['priority', 'label'],
            },
        ),
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('HIDE', 'Hide Menu'), ('VIEW', 'View Only'), ('FULL', 'Full Access')], default='HIDE', max_length=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='registry.accessmenu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='registry.roledefinition')),
            ],
            options={
                'unique_together': {('role', 'menu')},
            },
        ),
        migrations.CreateModel(
            name='UserMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('HIDE', 'Hide Menu'), ('VIEW', 'View Only'), ('FULL', 'Full Access')], default='HIDE', max_length=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_overrides', to='registry.accessmenu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'menu')},
            },
        ),
    ]
