# Generated by Django 5.0.2 on 2026-03-17 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_accessmenu_roledefinition_rolemenupermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemenupermission',
            name='access_type',
            field=models.CharField(choices=[('HIDE', 'Hide Menu'), ('VIEW_ALL', 'View Only'), ('EDIT_STUDENTS', 'Edit Students'), ('EDIT_STAFF', 'Edit Staff'), ('EDIT_HOD', 'Edit HOD'), ('EDIT_DEAN', 'Edit Dean'), ('EDIT_STAFF_STUDENTS', 'Edit Staff Students'), ('EDIT_HOD_STAFF', 'Edit HOD Staff'), ('EDIT_HOD_STAFF_STUDENTS', 'Edit HOD Staff Students'), ('EDIT_ALL', 'Edit All'), ('FULL', 'Full Access')], default='HIDE', max_length=30),
        ),
        migrations.AlterField(
            model_name='usermenupermission',
            name='access_type',
            field=models.CharField(choices=[('HIDE', 'Hide Menu'), ('VIEW_ALL', 'View Only'), ('EDIT_STUDENTS', 'Edit Students'), ('EDIT_STAFF', 'Edit Staff'), ('EDIT_HOD', 'Edit HOD'), ('EDIT_DEAN', 'Edit Dean'), ('EDIT_STAFF_STUDENTS', 'Edit Staff Students'), ('EDIT_HOD_STAFF', 'Edit HOD Staff'), ('EDIT_HOD_STAFF_STUDENTS', 'Edit HOD Staff Students'), ('EDIT_ALL', 'Edit All'), ('FULL', 'Full Access')], default='HIDE', max_length=30),
        ),
        migrations.CreateModel(
            name='AssessmentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('CLOSED', 'Closed')], default='DRAFT', max_length=15)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='allowed_tests', to='registry.roledefinition')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOCKED', 'Locked'), ('PRESENT', 'Present'), ('ONGOING', 'Ongoing'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed')], default='LOCKED', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('total_marks', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invigilator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invigilated_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='registry.assessmenttest')),
            ],
            options={
                'unique_together': {('test', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('DESCRIPTIVE', 'Descriptive')], default='DESCRIPTIVE', max_length=20)),
                ('max_marks', models.FloatField(default=1.0)),
                ('mcq_options', models.JSONField(blank=True, default=list)),
                ('mcq_answer', models.JSONField(blank=True, default=list)),
                ('rubric', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='registry.assessmenttest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InvigilatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sessions', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_assignments', to='registry.assessmenttest')),
            ],
            options={
                'unique_together': {('test', 'invigilator')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('mcq_selection', models.JSONField(blank=True, default=list)),
                ('marks_awarded', models.FloatField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_responses', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='registry.studenttestsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.testquestion')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
