# Generated by Django 5.0.2 on 2026-03-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_alter_rolemenupermission_access_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestsession',
            name='invigilator_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
