# Generated by Django 5.0.2 on 2026-03-17 08:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_studenttestsession_invigilator_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='invigilatorassignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invigilatorassignment',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invigilatorassignment',
            name='declined_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invigilatorassignment',
            name='handshake_token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='invigilatorassignment',
            name='invitation_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='invigilatorassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='testattendance',
            name='attendance_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testattendance',
            name='attendance_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattendance',
            name='invigilator_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testattendance',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testattendance',
            name='proof_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='EvaluationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_marks', models.FloatField(blank=True, null=True)),
                ('new_marks', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_history', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='registry.questionresponse')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BLUR', 'Window Lost Focus'), ('TAB_SWITCH', 'Tab Switch'), ('COPY', 'Copy Attempt'), ('PASTE', 'Paste Attempt'), ('SCREENSHOT', 'Screenshot Attempt'), ('AI_TOOL', 'AI Tool Detected'), ('FOCUS_RETURN', 'Focus Restored')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_events', to='registry.studenttestsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSessionLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('last_violation_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_submit_triggered', models.BooleanField(default=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock_record', to='registry.studenttestsession')),
            ],
        ),
    ]
