# Generated by Django 5.0.2 on 2026-03-17 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_invigilatorassignment_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invigilatorassignment',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_assignments', to='registry.examinationtest'),
        ),
    ]
